name: furniture
favicon: null
layout_spectrum: 0.15570376883260906
typography_spectrum: 0.2783274604007602
title: CNC-Step iT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7904823420103639
  lightness: 0.5472722195554525
  saturation: 0.5167041034437716
  rhythmicContrast: 0.6858864759560674
purpose: []
