name: furniture
favicon: null
layout_spectrum: 0.15570376883260906
typography_spectrum: 0.2783274604007602
title: CNC-Step iT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1008'
    - '#dacf66'
    - '#47562d'
    - '#96a44f'
    - '#c02800'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5167041034437716
  rhythmicContrast: 0.75
purpose: []
